name: turmites
version: 0.0.7c
description: Droppers which can move like turmites
author: https://github.com/hilbix/
website: https://github.com/hilbix/turmites.git
main: net.geht.mc.turmites.Main
database: false
load: postworld
commands:
  turmite:
    description: Control turmites
    usage: |
      <command> subcommand [args..]
      <command> save BOOK -- save held book to file
      <command> load BOOK -- load book from file
      <command> book [BOOK] -- list books or show detail
      <command> exec X Y Z -- boot turmite at the given location
      <command> list [TASK] -- list all tasks or show details
      <command> slow [N] [M] -- run tasks with N/M steps per tick, default 1
      <command> stop TASK -- stop (terminate) tasks, 'all' for all
      <command> halt TASK -- halt task, 'all' for all
      <command> cont [TASK] -- continue task, default: last halted
      <command> step [COUNT] -- singlestep halted tasks
      <command> debug level [TASK] -- debug tasks, level=0(off) to 65535(full)
      <command> set key [value] -- get key value or set it
      <command> tool -- give the turmite tool (golden hoe)
    aliases: [t,tu,tur,turm,turmites]

permissions:
  turmite.*:
    description: Gives permission to all turmite commands
    children:
      turmite.save: true
      turmite.load: true
      turmite.book: true
      turmite.exec: true
      turmite.list: true
      turmite.slow: true
      turmite.stop: true
      turmite.ctrl: true
      turmite.debug: true
      turmite.set: true
  turmite.save:
    description: Allow "turmite save" command
    default: op
  turmite.load:
    description: Allow "turmite save" command
    default: op
  turmite.book:
    description: Allow "turmite save" command
    default: true
  turmite.exec:
    description: Allow "turmite exec" command
    default: op
  turmite.list:
    description: Allow "turmite list" command
    default: true
  turmite.slow:
    description: Allow "turmite slow" command
    default: op
  turmite.stop:
    description: Allow "turmite stop" command
    default: op
  turmite.ctrl:
    description: Allow "turmite halt|cont|step" commands
    default: op
  turmite.debug:
    description: Allow "turmite debug" command
    default: op
  turmite.set:
    description: Allow "turmite set" command
    default: op

